### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Simoneth** [ShiiRochi/wavesurfer-react#61]
Hi,
I upgraded React from v17 to v18 + Next.js from v12 to v13, and now this error happens:

```
error - unhandledRejection: /Users/mine/Sites/nextjs/myApp/node_modules/wavesurfer-react/dist/index.js:1
import Region from "./components/Region";
```
```
"react": "^18.2.0",
"next": "^13.0.6",
"wavesurfer-react": "^2.2.2",
 "wavesurfer.js": "^6.4.0",
```

I cannot use "type": "module", in my package.json otherwise it `Failed to load next.config.js`

Thanks in advance for any suggestions!

**Comment by Simoneth** [comment]
Here my Wavesurfer component:

```
import { WaveSurfer, WaveForm, Region } from "wavesurfer-react";
import RegionsPlugin from "wavesurfer.js/dist/plugin/wavesurfer.regions.min";
import TimelinePlugin from "wavesurfer.js/dist/plugin/wavesurfer.timeline.min";

export default function Wavesurfer(props) {
    const [timelineVis] = useState(true);
    const minSec = 5;
    const maxSec = 30;
    const absoluteMaxRegions = 20;
    const [maxRegions, setMaxRegions] = useState();

    const plugins = useMemo(() => {
        return [
            {
                plugin: RegionsPlugin,
                options: { dragSelection: true }
            },
            timelineVis && {
                plugin: TimelinePlugin,
                options: {
                    container: "#timeline" + props.id
                }
            }
        ].filter(Boolean);
    }, [timelineVis]);
    
    return (
        <WaveSurfer plugins={plugins} onMount={handleWSMount}>
            <WaveForm
                id={"waveform" + props.id}
                cursorColor="OrangeRed"
                progressColor="#00a3ff"
                barWidth="3"
                barRadius="3"
                responsive="true"
                partialRender="true"
            >
                {props.regions.map((regionProps) => (
                    <Region
                        onUpdateEnd={handleRegionUpdate}
                        key={regionProps.id}
                        minLength={minSec}
                        maxLength={maxSec}
                        maxRegions={maxRegions}
                        {...regionProps}
                    />
                ))}
            </WaveForm>

            <div className="timeline" id={"timeline" + props.id} />
        </WaveSurfer>
    )
```

And how I call it:

```
import dynamic from 'next/dynamic';
const Wavesurfer = dynamic(import('src/components/wavesurfer'), { ssr: false })
```

**Comment by ShiiRochi** [comment]
Hi, @Simoneth, check your dynamic import, according to the NextJS docs first argument has to be a function

[Dynamic Import](https://nextjs.org/docs/advanced-features/dynamic-import)

**Comment by Simoneth** [comment]
Thanks,
So, I changed to this:

```
const Wavesurfer = dynamic(() => import('src/components/wavesurfer'), {
  ssr: false,
})
```
The previous error has disappeared, but it doesn't solve the general problem for me:
<img width="835" alt="Screenshot 2023-01-23 at 11 14 12" src="https://user-images.githubusercontent.com/8775559/214015218-3c3f36cd-1328-4007-90e3-007466643680.png">

**Comment by ShiiRochi** [comment]
@Simoneth, I've created next-project
```
{
    ...,
    "next": "13.1.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "wavesurfer-react": "2.2.2",
    "wavesurfer.js": "6.4.0",
    ...
}
```
Within the project, I implemented the following component:
```
import { useCallback, useMemo, useRef, useState } from 'react';
import { WaveSurfer, WaveForm, Region, Marker } from 'wavesurfer-react';
import RegionsPlugin from 'wavesurfer.js/dist/plugin/wavesurfer.regions.min';
import TimelinePlugin from 'wavesurfer.js/dist/plugin/wavesurfer.timeline.min';
import MarkersPlugin from 'wavesurfer.js/src/plugin/markers';

export default function Wavesurfer({ id }) {
  const waveformId = 'waveform' + '-' + id;
  const timelineId = `timeline-${id}`;

  const plugins = useMemo(() => {
    return [
      {
        plugin: RegionsPlugin,
        options: { dragSelection: true },
      },
      {
        plugin: TimelinePlugin,
        options: {
          container: timelineId,
        },
      },
      {
        plugin: MarkersPlugin,
        options: {
          markers: [{ draggable: true }],
        },
      },
    ];
  }, [timelineId]);

  const [regions, setRegions] = useState([
    {
      id: 'region-1',
      start: 0.5,
      end: 10,
      color: 'rgba(0, 0, 0, .5)',
      data: {
        systemRegionId: 31,
      },
    },
    {
      id: 'region-2',
      start: 5,
      end: 25,
      color: 'rgba(225, 195, 100, .5)',
      data: {
        systemRegionId: 32,
      },
    },
    {
      id: 'region-3',
      start: 15,
      end: 35,
      color: 'rgba(25, 95, 195, .5)',
      data: {
        systemRegionId: 33,
      },
    },
  ]);

  const [markers, setMarkers] = useState([
    {
      time: 5.5,
      label: 'V1',
      color: '#ff990a',
      draggable: true,
    },
    {
      time: 10,
      label: 'V2',
      color: '#00ffcc',
      position: 'top',
    },
  ]);

  const wavesurferRef = useRef(null);

  const onWaveSurferMount = useCallback((waveSurfer) => {
    if (waveSurfer.markers) {
      waveSurfer.clearMarkers();
    }

    wavesurferRef.current = waveSurfer;

    if (wavesurferRef.current) {
      wavesurferRef.current.load('/audios/1.mp3');

      // wavesurferRef.current.on('region-created', regionCreatedHandler);

      wavesurferRef.current.on('ready', () => {
        console.log('WaveSurfer is ready');
      });

      wavesurferRef.current.on('region-removed', (region) => {
        console.log('region-removed --> ', region);
      });

      wavesurferRef.current.on('loading', (data) => {
        console.log('loading --> ', data);
      });

      if (window) {
        window.surferidze = wavesurferRef.current;
      }
    }
  }, []);

  return (
    <WaveSurfer plugins={plugins} onMount={onWaveSurferMount}>
      <WaveForm id={waveformId}>
        {regions.map((regionProps) => (
          <Region
            onUpdateEnd={() => {}}
            key={regionProps.id}
            {...regionProps}
          />
        ))}
        {markers.map((marker, index) => {
          return (
            <Marker
              key={index}
              {...marker}
              onClick={(...args) => {
                console.log('onClick', ...args);
              }}
              onDrag={(...args) => {
                console.log('onDrag', ...args);
              }}
              onDrop={(...args) => {
                console.log('onDrop', ...args);
              }}
            />
          );
        })}
      </WaveForm>
      <div id={timelineId}></div>
    </WaveSurfer>
  );
}
```

Firstly, I received the same error about container being not specified, but I found out that I made a mistake in plugins props. After the following change everything start to work:
```
  ...
  const plugins = useMemo(() => {
    return [
      {
        plugin: RegionsPlugin,
        options: { dragSelection: true },
      },
      {
        plugin: TimelinePlugin,
        options: {
          // old value was just timelineId
          container: '#' + timelineId,
        },
      },
      {
        plugin: MarkersPlugin,
        options: {
          markers: [{ draggable: true }],
        },
      },
    ];
  }, [timelineId]);
  ...
```

Thus, make sure that both id in plugins list and in div, that is considered to be a timeline container contain and receive (respectively) the same value, because currently timeline will not rebuild if some of its props would change.

**Comment by Simoneth** [comment]
Sorry again for the inconvenience but could you give me a link to see your example...that would really help, because I still can't figure it out.

Thanks!

**Comment by ShiiRochi** [comment]
@Simoneth, https://github.com/ShiiRochi/experimental-next-project

**Comment by Simoneth** [comment]
Thanks,
I finally figured out that mine was a re-rendering issue.
